version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak1s
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8089:8080"
    command: ["start-dev"]
    volumes:
      - ./keycloak_data:/opt/keycloak/data