spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=123
server.port=8084
# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
#eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

## keycloak
keycloak.admin.url=http://localhost:8089/auth/admin
keycloak.realm=SkinMatch
keycloak.adminClientId=backendSkinMatch
keycloak.adminClientSecret=cAULNX7HEfftCzwFsYCsm2a0bXvDT1J3
keycloak.urls.auth=http://localhost:8089